using System.Collections.Generic;

namespace DataStruct
{
    /// <summary>
    /// 数据结构基类
    /// </summary>
    public abstract class DataStructBase
    {
        /// <summary>
        /// 加载
        /// </summary>
        /// <param name="filename">文件名</param>
        /// <param name="section">段落名</param>
        /// <returns>OK:成功,其他:失败</returns>
        public abstract Errortype Load(string filename, string section);

        /// <summary>
        /// 保存
        /// </summary>
        /// <param name="fileName">文件名</param>
        /// <param name="section">段落名</param>
        /// <returns>OK:成功,其他:失败</returns>
        public abstract Errortype Save(string fileName, string section);
    }

    /// <summary>
    /// 错误类型
    /// </summary>
    public enum Errortype
    {
        OK = 0,
        UNKNOW_ERROR = 1,
        SAVE_ERROR,
        SAVE_INPUT_NULL,
        CAMERA_DATA_NULL_ERROR,
        PARAMS_FILE_SAVE_ERROR,
        PARAMS_FILE_LOAD_ERROR,
        PARAMS_FILE_DIR_NOT_EXIST_ERROR,
        PARAMS_LOAD_FILE_NOT_EXIST,

        INTERNAL_ALGO_ERROR,
        CALIBRATE_ISNOT_COMPLET_ERROR,
        CALIB_ITEM_NAME_NULL,

        FOCUS_IMAGES_ERROR,
        FOCUS_AXIS_POINTS_ERROR,
        FOCUS_AXIS_POINTS_NULL,
        FOCUS_AXIS_POINTS_STEPERROR,
        FOCUS_AXIS_STEP_TOO_SMALL,
        FOCUS_FRONT_DECREASE,
        FOCUS_FRONT_INCREASE,
        FOCUS_VALUE_NULL,
        FOCUS_SCORE_RANGE_MINERROR,

        OPT_CALIBRATE_MARK_ERROR,
        OPT_CONCENTER_CALIBRATE_POINTS_ERROR,
        OPT_CONCENTER_CALIBRATE_POINTS_NUM_UNEQUAL,
        OPT_CONCENTER_CALIBRATE_POINTS_COLLINE,
        OPT_PIX_CALIBRATE_POINTS_ERROR,
        OPT_CALIBRATE_POINTS_SIZE_ERROR,
        OPT_NAME_REPEAT,
        OPT_NAME_NULL,
        OPT_INPUT_POINT_NULL,

        MACROSTAGE_LIST_COUNT_UNEQUAL,
        MACROSTAGE_ANGLE_DICTIONARY_COUNT_ERROR,
        MACROSTAGE_CALIB_POINTS_NUM_ERROR,
        MACROSTAGE_NAME_NULL,
        MACROSTAGE_NAME_REPEAT,
        MACROSTAGE_INPUT_POINT_NULL,

        NANOSTAGE_NAME_NULL,
        NANOSTAGE_NAME_REPEAT,
        NANOSTAGE_CALIB_POINTS_NUM_ERROR,
        NANOSTAGE_INPUT_POINT_NULL,

        AVM_CHUCK_CALIB_POINTS_NULL,
        AVM_CHUCK_CALIB_POINTS_NUM_ERROR,
        AVM_CHUCK_NAME_NULL,
        AVM_CHUCK_NAME_REPEAT,
        AVM_INPUT_POINT_NUM_ERROR,
        AVM_INPUT_POINT_NULL,
        AVM_INPUT_POINT_COUNT_ERROR,
        AVM_SOPTMAP_PARAM_ERROR,

        COMMONALGO_POLYGONPOINT_NUM_ERROR,
        COMMONALGO_POLYGONPOINT_DIST_ERROR,
        COMMONALGO_POINTSET_NUM_ERROR,
        COMMONALGO_LINESEG_NUM_ERROR,
        COMMONALGO_POINTSET_NUM_NOT_EQUAL,
        COMMONALGO_SORTMODE_ERROR,
        COMMONALGO_SORTPAIR_INPUT_NULL,
        COMMONALGO_SORTPAIR_INPUTLENGTH_NOT_EQUAL,
        COMMONALGO_SORTPAIR_INPUTLENGTH_ZERO,
        COMMONALGO_MATRIX_LENGTH_ERROR,
        COMMONALGO_MATRIX_INPUT_NULL,
        COMMONALGO_FITLINE_POINTS_NULL,
        COMMONALGO_CALCPOINTSRT_ROTATECENTER_NULL,
        COMMONALGO_CALCPOINTSRT_POINT_EMPTY,
        COMMONALGO_SORTROWCOLUMN_DISORDER,

        COMMONALGO_INPUT_LINE_PARALLEL,
        COMMONALGO_INPUT_LINE_COLLINEAR,
        COMMONALGO_INTERSECTIONLINES_NULL,

        COMMONALGO_MARK_SEARCH_FAIL,
        COMMONALGO_POINT_INPUT_NULL,
        COMMONALGO_CALCANGLELL_INPUT_NULL,
        COMMONALGO_GETRECTMARKCENTERPIX_IMG_NULL,
        COMMONALGO_GETRECTMARKCENTERPIX_IMG_ERROR,
        COMMONALGO_GETRECTMARKCENTERPIX_RECTREGION_ZERO,
        COMMONALGO_GETMARKCENTERPIX_INPUT_IMG_NULL,
        COMMONALGO_GETCIRCLEMARKCENTER_INPUT_CIRCLE_NULL,
        COMMONALGO_GETCIRCLEMARKCENTER_INPUT_CIRCLE_ERROR,
        COMMONALGO_CALCLIGHECENTER_ZEORCROSSING_ERROR,

        TEMPLATEMATCH_TEMPLATE_NULL,
        TEMPLATE_TYPE_LOAD_ERROR,
        TEMPLATE_CREATE_REGION_EMPTY,
        CREATE_TEMPLATE_ERROR,
        SAVE_TEMPLATE_COLLECTS_ERROR,
        MATCH_TEMPLATE_ERROR,
        READ_TEMPLATE_ERROR,
        READ_TEMPLATEREGION_ERROR,
        READ_TEMPLATEMASKREGION_ERROR,
        READ_TEMPLATEMATCHPARAM_ERROR,
        FIND_TEMPLATE_ZERO,
        TEMPLATE_CREATE_PARAMTYPE_ERROR,

        TEMPLATE_CREATE_EDGELINE_NULL,
        TEMPLATE_CREATE_EDGELINE_COUNT_ERROR,
        TEMPLATE_SHAPEXLD_TYPE_ERROR,
        TEMPLATE_RELEASE_REPEAT,
        TEMPLATE_CREATE_TYPE_ERROR,

        TEMPLATEMANAGER_IMAGE_NULL,
        TEMPLATEMANAGER_TEMPLATEREGION_NULL,
        TEMPLATEMANAGER_OBJECT_NULL,
        TEMPLATEMANAGER_OBJECT_NAME_NULL,
        TEMPLATEMANAGER_SAVE_OBJECT_NULL,
        TEMPLATEMANAGER_LOAD_OBJECT_NULL,
        TEMPLATEMANAGER_SAVE_DIR_NOT_EXIST,
        TEMPLATEMANAGER_LOAD_DIR_NOT_EXIST,
        TEMPLATEMANAGER_DELETE_DIR_NOT_EXIST,
        TEMPLATEMANAGER_LOAD_INFO_NOT_EXIST,
        TEMPLATEMANAGER_LOAD_NAME_NOT_EQUAL,
        TEMPLATEMANAGER_CREATE_PARAMS_ERROR,
        SAVE_MATCH_REGION_ERROR,
        GET_MATCH_REGION_ERROR,

        LINE_COUNT_ERROR,
        FILE_NOT_EXIST,
        NAME_NOT_EQUAL,
        LINE_CALIPER_NUM_NOT_EQUAL,
        CALIPER_LINE_NULL,
        CALIPER_CIRCLE_NULL,
        CALIPER_RECTANGLE_NULL,
        CALIPER_LINE_SHORT,
        CALIPER_LINE_POLARITY_POINT_OUT_OF_IMAGE,
        CALIPER_BAD_IMAGE_CONSTRAST,
        CALIPER_NUM_MINSOCRE,
        CALIPER_CIRCLEMARKEXRACTION_IMG_NULL,
        CALIPER_CIRCLEMARKEXRACTION_IS_TOO_BIG,
        CALIPER_CIRCLEMARKEXRACTION_MINMAXAREA_ARE_RIGHT,
        CALIPER_GETRECTMARKCENTERPIX_IMG_NULL,
        CALIPER_GETRECTMARKCENTERPIX_IMG_ERROR,
        CALIPER_GETRECTMARKCENTERPIX_RECTREGION_ZERO,

        READ_CALIPERPARAM_INDEX_ERROR,
        READ_CALIPERPARAM_VALUE_ERROR,

        READ_LINESEG_INDEX_ERROR,
        READ_LINESEG_VALUE_ERROR,

        READ_POINT_INDEX_ERROR,
        READ_POINT_VALUE_ERROR,

        READ_RECTANGLE1_INDEX_ERROR,
        READ_RECTANGLE1_VALUE_ERROR,

        READ_RECTANGLE2_INDEX_ERROR,
        READ_RECTANGLE2_VALUE_ERROR,

        READ_CIRCLE_INDEX_ERROR,
        READ_CIRCLE_VALUE_ERROR,

        READ_NCCMATCHPARAMS_INDEX_ERROR,
        READ_NCCMATCHPARAMS_VALUE_ERROR,

        READ_NCCTEMPLATEPARAMS_INDEX_ERROR,
        READ_NCCTEMPLATEPARAMS_VALUE_ERROR,

        READ_SHAPEMATCHPARAMS_INDEX_ERROR,
        READ_SHAPEMATCHPARAMS_VALUE_ERROR,

        READ_SHAPETEMPLATEPARAMS_INDEX_ERROR,
        READ_SHAPETEMPLATEPARAMS_VALUE_ERROR,

        INIT_MARKLOCATIONMANAGER_SIZE_NOT_EQUAL,
        SAVE_MARKLOCATIONMANAGER_SIZE_NOT_EQUAL,
        LOAD_MARKLOCATIONMANAGER_SIZE_NOT_EQUAL,
        SAVE_MARKLOCATIONMANAGER_OBJECT_NULL,
        LOAD_MARKLOCATIONMANAGER_OBJECT_NULL,

        MARKLOCATIONMANAGER_OBJECT_NULL,
        MARKLOCATIONMANAGER_NAME_NULL,
        MARKLOCATIONMANAGER_INPUTNAME_NULL,
        MARKLOCATIONMANAGER_IMAGE_NULL,
        MARKLOCATIONMANAGER_DIR_NOT_EXIST,
        MARKLOCATIONMANAGER_SHOWIMGFILE_NOT_EXIST,
        MARKLOCATIONMANAGER_NAME_REPEAT,
        MARKLOCATIONMANAGER_TYPE_NOT_MATCH,

        MARKLOCATIONCOMMON_LINE_NUM_ERROR,
        MARKLOCATIONCOMMON_LINE_NULL,
        MARKLOCATIONCOMMON_INPUT_NULL,
        MARKLOCATIONCOMMON_RESULT_NAN,
        MARKLOCATIONCOMMON_RESULT_NULL,
        MARKLOCATIONCOMMON_EDGELINENUM_ZERO,
        MARKLOCATIONCOMMON_EDGEREMOVELINENUM_ZERO,
        MARKLOCATIONCOMMON_EDGEADJUSTLINENUM_ZERO,
        MARKLOCATIONCOMMON_EDGEEXTRACTEDLINENUM_ZERO,

        EDGECONTOURS_NULL,

        INPUT_NULL,
        INPUT_POINTS_NULL,
        INPUT_IMAGE_NULL,
        INPUT_SIZE_NOT_EQUAL,
        CALIBDISTORT_ISNOT_COMPLET_ERROR,
        CALIBDISTORT_IMAGE_SIZE_ERROR,
        CALIBDISTORT_SAVE_FILEPATH_NULL,
        CALIBDISTORT_SAVE_FILEPATH_LENGTH_ERROR,
        CALIBDISTORT_SAVE_FILE_DIR_NOT_EXIST_ERROR,

        PATTERN_SOURCEIMG_NULL,
        PATTERN_PARTIMG_NULL,
        PATTERN_PARTIMG_EMPTY,
        PATTERN_INPUT_NULL,
        PATTERN_LINE_NULL,
        PATTERN_ORIGIN_OUTOFRANGE,

        HOMMAT_AFFINE_INPUT_NULL,
        HOMMAT_AFFINE_INPUT_SIZE_NOT_ERUQL,
        HOMMAT_AFFINE_INPUT_SIZE_NOT_ENOUGH,
        HOMMAT_AFFINE_POINT_COLLINE,

        HOMMAT_SIMILARITY_INPUT_NULL,
        HOMMAT_SIMILARITY_INPUT_SIZE_NOT_ERUQL,
        HOMMAT_SIMILARITY_INPUT_SIZE_NOT_ENOUGH,

        HOMMAT_RIGID_INPUT_NULL,
        HOMMAT_RIGID_INPUT_SIZE_NOT_ERUQL,
        HOMMAT_RIGID_INPUT_SIZE_NOT_ENOUGH,

        SLIDE_CHECK_IAMGE_NULL,
        SLIDE_CHECK_WAFER_GRAB_ERROR,
        AVM_SEARCH_MARK_ROUND_NUM_ERROR,
        AVM_SEARCH_MARK_STEP_ERROR,
        AVM_SEARCHPOINTS_MISSMATCH_TO_TEACHPOINTS,
        AVM_CHECKPOINTS_NUM_ERROR,
        AVM_FEEDBACK_WINSIZE_ERROR,
        AVM_FEEDBACK_ERFPARAM_ERROR,
        AVM_FEEDBACK_DATA_NUM_ERROR,

        XYT_CALCCENTER_POINTS_NULL,
        XYT_CALCCENTER_POINTS_NOT_ENOUGH,
        XYT_XYCALIB_NULL,
        XYT_ISCALIB_FALSE,
        XYT_SAVE_DIR_NOT_EXIST,
        XYT_CALIBXY_ISCALIB_FALSE,
        XYT_LOAD_DIR_NOT_EXIST,
        XYT_LOAD_FILE_NOT_EXIST,
        XYT_LOAD_KEY_LENGTH_ERROR,

        CALIBCOORD_INPUTPOINTS_NULL,
        CALIBCOORD_INPUTPOINTS_COUNT_NOT_EQUAL,
        CALIBCOORD_KDTREE_COUNT_ZERO,
        CALIBCOORD_TRANSTYPE_ERROR,
        CALIBCOORD_KDTREE_NULL,
        CALIBCOORD_INFO_FILE_NOT_EXIST,
        CALIBCOORD_ISNOT_COMPLET_ERROR,
        CALIBCOORD_SAVE_FILEPATH_NULL,
        CALIBCOORD_SAVE_FILEPATH_LENGTH_ERROR,
        CALIBCOORD_SAVE_FILE_DIR_NOT_EXIST_ERROR,
        CALIBCOORD_INFO_SECTION_NOT_EXIST,
        CALIBCOORD_INFO_VALUE_LENGTH_ERROR,
        CALIBCOORD_MATRIXSRC2DST_VALUE_LENGTH_ERROR,
        CALIBCOORD_MATRIXDST2SRC_VALUE_LENGTH_ERROR,
        CALIBCOORD_MATRIX_FILE_NOT_EXIST,
        CALIBCOORD_POINTS_FILE_NOT_EXIST,
        CALIBCOORD_SRC2DSTBYKDTREE_INPUTPOINT_NULL,

        FIT_CIRCLE_POINT_COLLINE,

        FUSIONMANAGER_CALIBCOAXIALITY_IMG_NULL,
        FUSIONMANAGER_CALIBPIX_BAD_MRAK,
        FUSIONMANAGER_SETBOTTOMWAFERINFO_FINDLEFTMARK_LENGTH_ERROR,
        FUSIONMANAGER_SETTOPWAFERINFO_FINDLEFTMARK_LENGTH_ERROR,
        FUSIONMANAGER_SETPECINFO_FINDLEFTMARK_LENGTH_ERROR,
        FUSIONMANAGER_SETPECINFO_FINDRIGHTMARK_LENGTH_ERROR,
        FUSIONMANAGER_SETFIRSTGAININFO_FINDLEFTMARK_LENGTH_ERROR,
        FUSIONMANAGER_SETFIRSTGAININFO_FINDRIGHTMARK_LENGTH_ERROR,
        FUSIONMANAGER_SETSECONDGAININFO_FINDLEFTMARK_LENGTH_ERROR,
        FUSIONMANAGER_SETSECONDGAININFO_FINDRIGHTMARK_LENGTH_ERROR,
        FUSIONMANAGER_CALIBPIX_DIR_ERROR,
        FUSIONMANAGER_COAXIALITY_ITEMNAME_ERROR,
        FUSIONMANAGER_COAXIALITY_POINTIN_NULL,
        FUSIONMANAGER_INPUT_NULL,
        FUSIONMANAGER_GETCALIBSTATUS_ITEMNAME_NULL,
        FUSIONMANAGER_CALCMMPPX_IMG_NULL,
        FUSIONMANAGER_SETPARAMINFO_INPUT_NULL,
        FUSIONMANAGER_SVAPARAMINFO_ITEMNAME_NULL,
        FUSIONMANAGER_SVAPARAMINFO_ITEMNAME_EMPTY,
        FUSIONMANAGER_FINDLINEINLEFTRIGHT_LINESEG_NULL,
        FUSIONMANAGER_FINDLINEINLEFTRIGHT_LINESEG_EMPTY,

        FUSION_RECORD_FILENAME_NULL,
        FUSION_RECORD_FILENAME_EMPTY,

        IMAGE_PREPROCESS_INPUT_NULL,

        UBT_CALIB_DATA_NUM_ERROR,
        UBT_WAFER_NOTCH_TEMPLATE_LOAD_ERROR,
        UBT_GLASS_NOTCH_TEMPLATE_LOAD_ERROR,
        UBT_CALIB_TABLEINFO_FILE_ERROR,
        UBT_CALIB_IMAGE_FAILED,
        UBT_CALIBXY_OUT_OF_RANGE,
        UBT_ROTATE_CENTER_CALIB_INCOMPLETE,
        UBT_ROTATE_CENTER_FILE_NOT_EXIST,
        UBT_ROTATE_CENTER_FILE_ERROR,
        UBT_CAMERA_REAL_CALIB_INCOMPLETE,
        UBT_CAMERA_REAL_CALIB_BAD,
        UBT_AXIS_CALIB_INCOMPLETE,
        UBT_PIX_REAL_CALIB_POINTS_NUM_ERROR,
        UBT_NOTCH_MODLE_AREA_ERROR,
        UBT_NOTCH_MODLE_FILE_ERROR,
        UBT_NOTCH_SEARCH_FAILED,
        UBT_CAMERA_DATA_NULL,
        UBT_WAFER_EDGE_DATA_SIZE_MISMATCH,
        UBT_EDGE_SEARCH_FAILED,
        UBT_LEFT_EDGE_ERROR,
        UBT_RIGHT_EDGE_ERROR,
        UBT_UP_EDGE_ERROR,
        UBT_DOWN_EDGE_ERROR,
        UBT_ALIGN_CHECK_ERROR,
        UBT_GRAB_EDGEINFO_FILE_ERROR,
        UBT_TEMPLATE_NAME_NULL,

        UBT_MEASURE_INPUT_POINTS_NULL,
        UBT_MEASURE_POINTS_MAP_NULL,
        UBT_MEASURE_COLOR_SET_ERROR,

        REAL_CALIB_TABLE_ANGLE_ERROR,

        UBD_CALIB_NAME_NULL,
        UBD_CAMCENTER_NULL,
        UBD_INPUT_POINT_NULL,
        UBD_INPUT_POINT_EQUAL,
        UBD_INPUT_POINT_NUT_EQUAL,
        UBD_INPUT_POINT_LENGTH_ERROR,
        UBD_HEAD_ANGLE_OUT_RANGE,
        UBD_ADD_ANGLE_NOT_COMPLETE,
        UBD_INPUT_ANGLE_NULL,
        UBD_INPUT_LINE_NULL,
        UBD_INPUT_LINE_NOT_ENOUGH,
        UBD_INPUT_PARAM_NULL,
        UBD_CALIB_CAMCENTER_NULL,
        UBD_PARAM_SET_ERROR,
        UBD_IC_MARK_PARAM_FILE_ERROR,
        UBD_INPUT_IMAGE_NULL,
        UBD_INPUT_POINT_NOT_EQUAL,
        UBD_CALCGLASSBONDACCURACY_PARAM_NULL,
        UBD_CALCGLASSBONDACCURACY_IMG_NUM_ERROR,
        UBD_CALCGLASSBONDACCURACY_RULER_POINTS_NUM_ERROR,
        UBD_CALCWAFERANGLE_INPUT_POINT_NULL,
        UBD_CALCWAFERANGLE_INPUT_POINT_LENGTH_ERROR,
        UBD_CALCGLASSICMARKCENTER_INPUT_IMG_NULL,
        UBD_CALCGLASSICMARKCENTER_GRAB_ERROR,
        UBD_GETXYTHETAOFFSET_TEACHPARAMPOINT_NULL,
        UBD_CALCWAFERANGLE_INPUT_POINT_EQUAL,
        UBD_CALCWAFERANGLE_DIE_NONE,
        UBD_WAFER_STAGE_PATH_ERROR,
        UBD_LOAD_MAP_ERROR,
        UBD_MAP_LENGTH_ERROR,
        UBD_SUB_POINTS_RADIUS_ERROR,
        UBD_SUB_POINTS_INPUT_ERROR,
        UBD_DIEISEXIST_INPUT_IMAGE_NULL,

        UBH_INPUT_IMG_NULL,
        UBH_INPUT_PARAM_NULL,
        UBH_INPUT_LINE_NULL,
        UBH_INPUT_LINE_NOT_ENOUGH,
        UBH_INPUT_POINT_NULL,
        UBH_INPUT_POINT_EQUAL,
        UBH_INPUT_POINT_NOT_EQUAL,
        UBH_INPUT_POINT_COUNT_NOT_EQUAAL_TWO,
        UBH_INPUT_POINT_COUNT_LESS_ONE,
        UBH_INPUT_POINT_COUNT_LESS_TWO,
        UBH_INPUT_POINT_COUNT_LESS_THREE,
        UBH_CALIB_NAME_NULL,
        UBH_CONTOUR_NUMBER_IS_LESS_THAN,
        UBH_INTERSECTION_LESS_ONE,
        UBH_INPUT_POINT_LENGTH_ERROR,
        UBH_NOTCH_PEAK_IS_LESS_ONE,
        UBH_WAFERCIRCLE_IS_NOT_ONE,
        UBH_FILE_PATH_IS_NOT_EXIST,
        UBH_RESULT_COUNT_IS_LESS_ONE,

        UBC_INPUT_POINT_COUNT_ERROR,
        UBC_ANGLEDATA_IS_ERROR,
        UBC_CALIBROTATEANGLE_INFO_FILE_NOT_EXIST,
        UBC_INPUT_IMAGE_NULL,
        UBC_RECORDLOG_IS_NULL,
        UBC_XLD_SEGMENT_LESS_TWO,
        UBC_CIRCULARITY_SELECT_LESS_ONE,
        UBC_XLD_CIRCULARITY_SELECT_LESS_ONE,
        UBC_AREA_SELECT_NOT_EQUAL_ONE,
        UBC_AREA_SELECT_NOT_REASONABLE,
        UBC_XLD_AREA_SELECT_NOT_EQUAL_ONE,
        UBC_INPUT_COUNT_NOT_EQUAAL_TWO,
        UBC_INPUT_COUNT_NOT_EQUAAL_THREE,
        UBC_INPUT_COUNT_IS_LESS_TWO,
        INPUT_POINT_ERROR,

        CALIBPARAM_LEFTCAMNAME_EMPYT,
        CALIBPARAM_RIGHTCAMNAME_EMPYT,
        CALIBPARAM_LEFTSCALE_ZERO,
        CALIBPARAM_RIGHTSCALE_ZERO,
        CALIBPARAM_IMGCENTER_NULL,
        CALIBPARAM_IMGCENTER_ZERO,

        UBA_CALIBPARAM_NULL,
        UBA_CALCTR_INPUT_NULL,
        UBA_BASEWAFER_INFO_NULL,
        UBA_CROPIMG_IMAGE_NULL,
        UBA_CROPIMG_INPUT_POINT_NULL,
        UBA_CROPIMG_INPUT_POINT_LITTLE,
        UBA_SETOFFSET_INPUT_POINT_NULL,
        UBA_TRANSXYY_OUTOFLIMIT,

        IRDETECTION_CALIB_NULL,
        IRDETECTION_SELECTEDREGION_NULL,
        IRDETECTION_CALCTANGENTLINEDIST_IMG_NULL,
        IRDETECTION_CALIB_IMG_NULL,

        IMAGEEMPHASIZE_GAUSSSIZE_ERROR,

        RANSAC_SAMPLE_COUNT_ERROR,
        RANSAC_SAMPLE_INDEX_ERROR,

        FILE_NO_WRITE_PERMISSION,

        CALIBPIX_INIT_ITEMNAME_NULL,
        CALIBPIX_ISNOT_COMPLET_ERROR,
        CALIBPIX_SAVE_FILEPATH_NULL,
        CALIBPIX_SAVE_FILEPATH_EMPTY,
        CALIBPIX_SAVE_FILE_DIR_NOT_EXIST_ERROR,
        CALIBPIX_CALIBRULERSCALE_INPUT_EQUAL,
        CALIBPIX_CALIBRULERSCALE_INPUT_NULL,

        CALIBPIXSCALEXY_ISNOT_COMPLET_ERROR,
        CALIBPIXSCALEXY_INIT_ITEMNAME_NULL,
        CALIBPIXSCALEXY_SAVE_FILEPATH_NULL,
        CALIBPIXSCALEXY_SAVE_FILEPATH_EMPTY,
        CALIBPIXSCALEXY_SAVE_FILE_DIR_NOT_EXIST_ERROR,
        CALIBPIXSCALEXY_CALIBRULERSCALE_INPUT_EQUAL,
        CALIBPIXSCALEXY_CALIBRULERSCALE_INPUT_NULL,

        CALIBXYT_INIT_ITEMNAME_NULL,
        CalibXYT_INITCALIBROTATECENTER_CALIBCOORD_NULL,
        CALIBXYT_ISNOT_COMPLET_ERROR,
        CALIBXYT_SAVE_FILEPATH_NULL,
        CALIBXYT_SAVE_FILEPATH_EMPTY,
        CALIBXYT_SAVE_FILE_DIR_NOT_EXIST_ERROR,
        CALIBXYT_LOAD_FILEPATH_NULL,
        CALIBXYT_lOAD_FILEPATH_EMPTY,

        CALIBXY_INIT_ITEMNAME_NULL,

        DIEBONDCOMMALGO_CALCWAFERANGLE_INPUT_POINTS_NULL,
        DIEBONDCOMMALGO_CALCWAFERANGLE_INPUT_POINTS_EQUAL,
        DIEBONDCOMMALGO_CALCCUTPATHCORNER_INPUT_IMAGE_NULL,
        DIEBONDCOMMALGO_CALCCUTPATHCORNER_INPUT_IMAGE_ERROR,
        DIEBONDCOMMALGO_CALCCIRCLERINGMARKCENTER_IMAGE_NULL,

        REPEATANALYSIS_GENREPEATREPORT_DATA_LENGTH_ERROR,
        REPEATANALYSIS_GENREPEATREPORT_DATA_ZERO,
        REPEATANALYSIS_SEPTITLE_TITLE_DATA_LENGTH_NOT_EQUAL,
    }

    /// <summary>
    /// 笛卡尔坐标轴
    /// </summary>
    public enum Axis
    {
        X,
        Y,
        Z,
    }

    /// <summary>
    /// 标定类型
    /// </summary>
    public enum CalibType : int
    {
        UNKNOW,

        // UBF
        OPTIC_CONCENTERIC, // 同心度
        OPTIC_EXTERNAL,    // 像素比，夹角
        OPTIC_UNION, // 真值坐标标定，轴运动ruler <-> real
        STAGE_MACRO, // 宏动平台
        STAGE_NANO,  // 微动平台
        STAGE_CHUCK,  // chuck

        //UBD新增
        OPTIC_INTERNAL, //相机畸变
        OPTIC_MOTION,   //运动系标定（ruler—real）
        ROTATE_CENTER,  //旋转中心标定
    }

    /// <summary>
    /// 标定板坐标系类型及旋转角度（用于旋转中心标定）
    /// </summary>
    public enum CalibRotateType : int
    {
        // 标定板右手坐标系对应的旋转0°、90°、180°、270°
        Calib_RIGHT_0,
        Calib_RIGHT_90,
        Calib_RIGHT_180,
        Calib_RIGHT_270,

        // 标定板左手坐标系对应的旋转0°、90°、180°、270°
        Calib_LEFT_0,
        Calib_LEFT_90,
        Calib_LEFT_180,
        Calib_LEFT_270,
    }

    /// <summary>
    /// 工作站
    /// </summary>
    public enum WorkStation
    {
        Left_Station,
        Right_Station,
    }
}